services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: librarydb
      MYSQL_USER: libraryuser
      MYSQL_PASSWORD: librarypass
    ports:
      - "3306:3306"
    volumes:
      - db_store:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: pathum2002/personal-library-backend:latest
    # No host port published; frontend proxies to backend:4000 internally
    restart: unless-stopped
    env_file:
      - Backend/.env
    environment:
      # Fallbacks if env_file missing
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/librarydb}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-libraryuser}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-librarypass}
    volumes:
      - backend_data:/app/data
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: pathum2002/personal-library-frontend:latest
    ports:
      - "3008:80"
    restart: unless-stopped
    volumes:
      - frontend_data:/usr/share/nginx/html/data
    depends_on:
      backend:
        condition: service_healthy

volumes:
  db_store:
  backend_data:
  frontend_data:
